---
- hosts: "{{ mysql }}"
  remote_user: test
  vars_files:
    - vars/server.yml
  tasks:
    - name: mysql_1
      #command: echo 'mysql'
      command: tar -xzf /root/mysqlstore.tar.gz -C /docker/volumes/
    - name: mysql_2
      command: docker run -d --name mysql  -p 13306:3306  -v  mysqlstore:/var/lib/mysql  -e MYSQL_ROOT_PASSWORD=passwd 192.168.2.217:5000/mysql
      #command: echo "asd :\"{{ mongo }}\""
