---
- hosts: "{{ master }},{{store}}"
  remote_user: root
  gather_facts: false
  ignore_errors: True
  vars_files:
    - ../vars/server.yml
  tasks:
    - name: masterInfo
      command: python /home/systemmonitor/info.py
      when: inventory_hostname in "{{master}}"
    - name: storeInfo
      command: python /home/systemmonitor/info.py
      when: inventory_hostname in "{{store}}"
