---
- hosts: "{{ master }}"
  remote_user: root
  gather_facts: false
  vars_files:
    - ../vars/server.yml
  tasks:
      #    - name: stop gateway service
      # command: docker service rm gw
    - name: stop gateway 
      command: docker stop gw
    - name: rm gateway 
      command: docker rm gw
