---
- hosts: "{{ mysql }}"
  remote_user: root
  gather_facts: false
  vars_files:
    - ../vars/server.yml
  tasks:
    - name: stop mysql
      command: docker stop mysql
    - name: rm mysql
      command: docker rm mysql
    - name: clear mysql
      command: rm -rf /docker/volumes/mysqlstore/
