---
- hosts: "{{ master }}"
  remote_user: root
  gather_facts: false
  vars_files:
    - vars/server.yml  
  tasks:
    - name: gw
      command: docker run -d  --restart=always --name gw -v /tmp:/root/data -p 9000:9000 -p 80:9000 192.168.2.217:5000/new_gw bash -c " rm -rf /root/data/* &&  /usr/local/bin/minio server --dbAddress "{{ master }}":37017 --metaDataAddress "{{ master }}":9333 --beanstalkdAddress "{{ master }}":11300 /root/data"
