---
- hosts: "{{ store }}"
  remote_user: root
  gather_facts: false
  vars_files:
    - vars/server.yml
  tasks:
     - name: begin to build raid,vol,fs
       command: python /home/monitor/store.py build
       register: foo_result
     - name: join master
       command: python /home/monitor/config.py --mserver=""{{ storeaim }}":9333" --ip=""{{ inventory_hostname }}""
       when: foo_result.stdout == "success"
     - name: join master
       command: '/etc/init.d/supervisor restart'
       when: foo_result.stdout == "success"
