---
- hosts: "{{ master }}"
  remote_user: root
  gather_facts: false
  vars_files:
    - vars/server.yml  
  tasks:
    - name: web
      command: docker service create  --name web -p 8081:8081  --mode=global 192.168.2.217:5000/web  python  /root/Server/cloudserver.py --mongo=""{{ mongo }}":37017" --mysql=""{{ mysql }}":13306" --url112=""{{ master }}"" --url812=""{{ master }}":9000" --down=""{{ master }}":9002"
